#!/bin/sh

ARD_PRODID="2341/0043/1"
SYMLINK="arduino_sensors"

if[ "${PRODUCT}" = "${ARD_PRODID}" ];
	then if [ "${ACTION}" = "add" ];
		then
		DEVICE_NAME = $(ls /sys/$DEVPATH | grep tty)
		logger -t Hotplug Device name of ARD is $DEVICE_NAME
		ln -s /dev/$DEVICE NAME /dev/${SYMLINK}
		logger -t Hotplug Symlink from /dev/$DEVICE_NAME to /dev/${SYMLINK} created
	fi
fi

if [ "${PRODUCT}" = "${ARD_PRODID}" ];
	then if [ "${ACTION}" = "remove" ];
		then
		rm /dev/${SYMLINK}
		logger -t Hotplug Symlink /dev/${SYMLINK} removed
	fi
fi
